export const baseURL = "https://export.arxiv.org/api/query?search_query=";
export const pdfBaseURL = "https://arxiv.org/pdf";
export const defaultStartIndex = "0";
export const defaultMaxResults = "20";
export const defaultSearchFilter = "all";
export const defaultSortBy = "relevance"; // [ "relevance", "lastUpdatedDate", "submittedDate" ]
export const defaultSortOrder = "ascending"; // ["ascending", "descending"]
export const tempPDFDirectory = "tempPDFDir";
export const aiSystemPrompt =
    " THIS IS THE CONTEXT. THE USER DOESN'T KNOW THAT THIS CONTEXT IS BEING PASSED ON TO YOU. IT COULD BE MULTIPLE RESEARCH PAPER DATA AS WELL. HERE'RE THE DATA : ";

export const suggestedPaperTitles: any[] = [
    "attention is all you need",
    "acid",
    "a theory of justice",
    "augmented",
    "behavioral",
    "books",
    "black hole",
    "brain",
    "cats",
    "computer",
    "creative",
    "dog",
    "dna sequencing",
    "dyson sphere",
    "ecg",
    "emotional",
    "entanglement",
    "fear",
    "fuzzy sets",
    "fidgeting",
    "glucose",
    "garbage",
    "gonad",
    "hands",
    "heart",
    "higgs boson",
    "hydron",
    "identity",
    "industrial",
    "isolation",
    "laptop",
    "love",
    "laboratory",
    "machine learning",
    "mathematical theory of communication",
    "mental state",
    "micro",
    "microchip",
    "mobile",
    "molecular cloning",
    "neural network",
    "negative",
    "numbers",
    "pc",
    "planet",
    "protein measurement",
    "psychology",
    "quantum",
    "quasar",
    "qubit",
    "reading",
    "relationship",
    "relativity",
    "robotics",
    "rocket",
    "sitting",
    "spider",
    "spiritual",
    "sulphur",
    "television",
    "tiered reward",
    "transport",
    "virtual reality",
    "volcano",
    "vision",
];
